import { Workflow } from '../types/workflow'

export const calculatorBasicArithmetic: Workflow = {
  id: 'calculator_basic_arithmetic',
  application: 'calculator',
  task: 'basic_arithmetic',
  name: 'Basic Arithmetic Calculation',
  description: 'Perform a basic addition calculation in Windows Calculator',
  levels: [
    {
      levelNumber: 1,
      id: 'click_first_number',
      title: 'Click first number',
      instruction: 'Click on a number button on the calculator keypad (e.g. 5).',
      voiceInstruction: 'Click the first number on the calculator keypad.',
      targetType: 'BUTTON',
      targetText: '5',
      targetDescription: 'The number 5 button on the Windows Calculator numeric keypad',
      expectedBeforeState: 'Calculator open displaying 0',
      expectedAction: 'User clicks number 5',
      expectedAfterState: 'Calculator display shows 5',
      completionCondition: 'First number is entered into calculator',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'click_plus_operator',
      title: 'Click plus operator',
      instruction: 'Click the "+" (plus) button to add.',
      voiceInstruction: 'Click the plus button.',
      targetType: 'BUTTON',
      targetText: 'plus',
      targetDescription: 'The addition (+) operator button on the calculator',
      expectedBeforeState: 'First number entered',
      expectedAction: 'User clicks plus button',
      expectedAfterState: 'Plus operator is active',
      completionCondition: 'Plus operator is selected',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'click_second_number',
      title: 'Click second number',
      instruction: 'Click the second number button (e.g. 3).',
      voiceInstruction: 'Click the second number.',
      targetType: 'BUTTON',
      targetText: '3',
      targetDescription: 'The number 3 button on the calculator keypad',
      expectedBeforeState: 'Operator active',
      expectedAction: 'User clicks number 3',
      expectedAfterState: 'Display shows second number',
      completionCondition: 'Second number is entered',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'click_equals',
      title: 'Click equals',
      instruction: 'Click the "=" (equals) button to compute the result.',
      voiceInstruction: 'Click equals to calculate the result.',
      targetType: 'BUTTON',
      targetText: 'equals',
      targetDescription: 'The Equals (=) button on the calculator keypad',
      expectedBeforeState: 'Expression ready to evaluate',
      expectedAction: 'User clicks equals button',
      expectedAfterState: 'Calculator result is displayed on screen',
      completionCondition: 'Calculation result is displayed',
      verificationMethod: 'visual_state_change',
    },
  ],
}
