import { Workflow } from '../types/workflow'

export const calculatorScientificMode: Workflow = {
  id: 'calculator_scientific_mode',
  application: 'calculator',
  task: 'scientific_mode',
  name: 'Switch to Scientific Mode',
  description: 'Switch Windows Calculator to Scientific mode and use functions',
  levels: [
    {
      levelNumber: 1,
      id: 'open_navigation_menu',
      title: 'Click menu icon',
      instruction: 'Click the menu button (three horizontal lines) in the top-left corner.',
      voiceInstruction: 'Click the menu icon in the top left.',
      targetType: 'BUTTON',
      targetText: 'menu',
      targetDescription: 'The navigation hamburger menu button in the top left of Calculator',
      expectedBeforeState: 'Standard calculator mode active',
      expectedAction: 'User clicks menu button',
      expectedAfterState: 'Calculator modes navigation drawer opens',
      completionCondition: 'Navigation menu is open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'select_scientific_mode',
      title: 'Click Scientific',
      instruction: 'In the menu drawer, click "Scientific".',
      voiceInstruction: 'Click Scientific in the menu.',
      targetType: 'BUTTON',
      targetText: 'scientific',
      targetDescription: 'The Scientific calculator mode option in the navigation drawer',
      expectedBeforeState: 'Navigation drawer open',
      expectedAction: 'User clicks Scientific mode',
      expectedAfterState: 'Calculator switches to Scientific mode with trigonometric and logarithmic buttons',
      completionCondition: 'Scientific calculator mode is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'enter_number',
      title: 'Enter a number',
      instruction: 'Click a number on the keypad (e.g. 9 or 16).',
      voiceInstruction: 'Enter a number on the keypad.',
      targetType: 'BUTTON',
      targetText: '9',
      targetDescription: 'A number button on the scientific keypad',
      expectedBeforeState: 'Scientific mode visible',
      expectedAction: 'User clicks a number',
      expectedAfterState: 'Number is displayed in calculator',
      completionCondition: 'Number is entered in scientific mode',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'click_square_root',
      title: 'Click square root (or function)',
      instruction: 'Click the square root (√) or another scientific function to compute.',
      voiceInstruction: 'Click square root or a scientific function.',
      targetType: 'BUTTON',
      targetText: 'square root',
      targetDescription: 'The square root (√) or function button in scientific mode',
      expectedBeforeState: 'Number entered',
      expectedAction: 'User clicks scientific function button',
      expectedAfterState: 'Calculated function result appears on display',
      completionCondition: 'Scientific calculation result is displayed',
      verificationMethod: 'visual_state_change',
    },
  ],
}
