import { Workflow } from '../types/workflow'

export const canvaResizeDesign: Workflow = {
  id: 'canva_resize_design',
  application: 'canva',
  task: 'resize_design',
  name: 'Resize Canvas Design',
  description: 'Resize your Canva design to custom dimensions or preset templates',
  levels: [
    {
      levelNumber: 1,
      id: 'click_resize_button',
      title: 'Click Resize / Magic Switch',
      instruction: 'In the top-left toolbar, click "Resize" or "Magic Switch".',
      voiceInstruction: 'Click Resize or Magic Switch in the top menu bar.',
      targetType: 'BUTTON',
      targetText: 'Resize',
      targetDescription: 'The Resize / Magic Switch button in the top menu bar of Canva',
      expectedBeforeState: 'Canva design open',
      expectedAction: 'User clicks Resize or Magic Switch',
      expectedAfterState: 'Resize / Magic Switch modal dialog opens',
      completionCondition: 'Resize modal dialog is open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'choose_custom_size',
      title: 'Click Custom size',
      instruction: 'In the dialog, click "Custom size" (or select a preset like Instagram Post).',
      voiceInstruction: 'Click Custom size or pick a preset.',
      targetType: 'BUTTON',
      targetText: 'Custom size',
      targetDescription: 'The Custom size option or preset format in the resize modal',
      expectedBeforeState: 'Resize modal open',
      expectedAction: 'User clicks Custom size',
      expectedAfterState: 'Width and Height input boxes appear',
      completionCondition: 'Dimension input fields are visible',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'apply_resize_action',
      title: 'Click Continue / Resize',
      instruction: 'Click "Continue" or "Resize this design" to apply the new dimensions.',
      voiceInstruction: 'Click Continue or Resize to apply changes.',
      targetType: 'BUTTON',
      targetText: 'Continue',
      targetDescription: 'The Continue or Resize action button at the bottom of the modal',
      expectedBeforeState: 'Dimensions entered or preset selected',
      expectedAction: 'User clicks Continue / Resize',
      expectedAfterState: 'Canvas adapts to the new dimensions',
      completionCondition: 'Design dimensions have updated',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_new_canvas_size',
      title: 'Verify canvas resized',
      instruction: 'Verify that the canvas aspect ratio and dimensions have updated.',
      voiceInstruction: 'Verify that your canvas dimensions have updated.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Design Canvas',
      targetDescription: 'The newly proportioned Canva canvas workspace',
      expectedBeforeState: 'Resize applied',
      expectedAction: 'User reviews new canvas aspect ratio',
      expectedAfterState: 'Canvas displays with new aspect ratio and layout',
      completionCondition: 'Canvas has resized successfully',
      verificationMethod: 'visual_state_change',
    },
  ],
}
