import { Workflow } from '../types/workflow'

export const canvaRemoveBackground: Workflow = {
  id: 'canva_remove_background',
  application: 'canva',
  task: 'remove_background',
  name: 'Remove Background',
  description: 'Remove background from an image in Canva',
  levels: [
    {
      levelNumber: 1,
      id: 'select_image',
      title: 'Select the image',
      instruction: 'Click on the image or poster on your canvas to select it.',
      voiceInstruction: 'Click on the image on your canvas to select it.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Image on Canvas',
      targetDescription: 'The central visual image, photo, or poster element placed on the Canva design canvas workspace',
      expectedBeforeState: 'Image is unselected on the Canva canvas (no purple border outline)',
      expectedAction: 'User clicks on the image on the canvas',
      expectedAfterState: 'Canva renders a purple selection border around the image and displays the contextual toolbar with "BG Remover" or "Edit"',
      completionCondition: 'A purple selection outline (#8B3DFF) or top editor toolbar appears',
      verificationMethod: 'canva_selection',
    },
    {
      levelNumber: 2,
      id: 'click_bg_remover',
      title: 'Click BG Remover',
      instruction: 'In the top toolbar directly above your image, click "BG Remover" (or click "Edit" if visible).',
      voiceInstruction: 'Click BG Remover in the toolbar above your image.',
      targetType: 'BUTTON',
      targetText: 'BG Remover',
      targetDescription: 'The "BG Remover" shortcut button or "Edit" button located in the contextual editor toolbar',
      expectedBeforeState: 'Image is selected with top toolbar visible',
      expectedAction: 'User clicks BG Remover or Edit',
      expectedAfterState: 'Canva initiates background removal or opens the Magic Studio panel',
      completionCondition: 'Background removal effect or Magic Studio panel is triggered',
      verificationMethod: 'bg_removal_complete',
    },
    {
      levelNumber: 3,
      id: 'apply_removal_effect',
      title: 'Apply background removal',
      instruction: 'If the left Magic Studio panel opened, click "BG Remover". Otherwise, Canva is processing the cutout.',
      voiceInstruction: 'Click BG Remover in the panel to apply the cutout.',
      targetType: 'BUTTON',
      targetText: 'BG Remover',
      targetDescription: 'The BG Remover tool card inside Magic Studio',
      expectedBeforeState: 'Magic Studio panel open or removal processing',
      expectedAction: 'User confirms background removal',
      expectedAfterState: 'Canva erases the surrounding background pixels',
      completionCondition: 'Background remover effect completes',
      verificationMethod: 'bg_removal_complete',
    },
    {
      levelNumber: 4,
      id: 'verify_removal',
      title: 'Verify background removed',
      instruction: 'Review the canvas to verify the background has been successfully removed.',
      voiceInstruction: 'Verify that the background has been removed.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Processed Canvas',
      targetDescription: 'The canvas area showing the transparent subject',
      expectedBeforeState: 'Background removal in progress or complete',
      expectedAction: 'User confirms result',
      expectedAfterState: 'Subject is isolated with transparent background',
      completionCondition: 'Subject is isolated on the canvas',
      verificationMethod: 'visual_state_change',
    },
  ],
}
