import { Workflow } from '../types/workflow'

export const canvaAnimation: Workflow = {
  id: 'canva_animation',
  application: 'canva',
  task: 'add_animation',
  name: 'Add Animation',
  description: 'Add motion or animation to a Canva element',
  levels: [
    {
      levelNumber: 1,
      id: 'select_element',
      title: 'Select element',
      instruction: 'Click on the text or graphic element on your canvas you want to animate.',
      voiceInstruction: 'Select the element on your canvas you want to animate.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Element on Canvas',
      targetDescription: 'The text or graphic object placed on the central design canvas',
      expectedBeforeState: 'Element is unselected on the Canva canvas',
      expectedAction: 'User clicks on the element on the canvas',
      expectedAfterState: 'Canva renders a purple selection border around the element and displays top toolbar with "Animate"',
      completionCondition: 'Element is selected with purple selection outline',
      verificationMethod: 'canva_selection',
    },
    {
      levelNumber: 2,
      id: 'click_animate',
      title: 'Click Animate',
      instruction: 'In the top Canva toolbar, click "Animate".',
      voiceInstruction: 'Click Animate in the top toolbar.',
      targetType: 'BUTTON',
      targetText: 'Animate',
      targetDescription: 'The "Animate" button in the top contextual editor toolbar',
      expectedBeforeState: 'Element is selected, Animate sidebar is closed',
      expectedAction: 'User clicks Animate in the top toolbar',
      expectedAfterState: 'The left sidebar panel opens displaying animation options like Fade, Pan, Rise, and Pop',
      completionCondition: 'Animation styles sidebar is open on the left',
      verificationMethod: 'animation_panel_appearance',
    },
    {
      levelNumber: 3,
      id: 'choose_style',
      title: 'Choose animation style',
      instruction: 'In the left panel, click on an animation style like "Fade", "Pan", or "Rise".',
      voiceInstruction: 'Choose an animation style from the left panel.',
      targetType: 'BUTTON',
      targetText: 'Fade',
      targetDescription: 'An animation style preset button such as Fade, Pan, or Rise in the left panel',
      expectedBeforeState: 'Animation panel open on the left',
      expectedAction: 'User clicks an animation style preset',
      expectedAfterState: 'Animation preset is applied to the selected element',
      completionCondition: 'Animation style is selected and applied',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_animation',
      title: 'Verify animation',
      instruction: 'Check that the animation icon or indicator is active on your element.',
      voiceInstruction: 'Verify that the animation is applied.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Animated Canvas',
      targetDescription: 'The canvas element with animation active',
      expectedBeforeState: 'Animation applied',
      expectedAction: 'User verifies the motion',
      expectedAfterState: 'Element shows active animation state',
      completionCondition: 'Animation active on element',
      verificationMethod: 'visual_state_change',
    },
  ],
}
