import { Workflow } from '../types/workflow'

export const canvaRemoveBackground: Workflow = {
  id: 'canva_remove_background',
  application: 'canva',
  task: 'remove_background',
  name: 'Remove Background',
  description: 'Remove background from an image in Canva',
  levels: [
    {
      levelNumber: 1,
      id: 'select_image',
      title: 'Select the image',
      instruction: 'Click on the image or poster on your canvas to select it.',
      voiceInstruction: 'Click on the image on your canvas to select it.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Image on Canvas',
      targetDescription: 'The central visual image, photo, or poster element placed on the Canva design canvas workspace',
      expectedBeforeState: 'Image is unselected on the Canva canvas (no purple border outline)',
      expectedAction: 'User clicks on the image on the canvas',
      expectedAfterState: 'Canva renders a purple selection border around the image and displays the top contextual toolbar with "Edit photo" or "Edit"',
      completionCondition: 'A purple selection outline (#8B3DFF) or top editor toolbar appears',
      verificationMethod: 'canva_selection',
    },
    {
      levelNumber: 2,
      id: 'click_edit_photo',
      title: 'Click Edit photo',
      instruction: 'In the top Canva toolbar, click "Edit photo" (or "Edit").',
      voiceInstruction: 'Now click Edit photo in the top toolbar.',
      targetType: 'BUTTON',
      targetText: 'Edit photo',
      targetDescription: 'The "Edit photo" or "Edit" button located in the top contextual editor toolbar',
      expectedBeforeState: 'Image is selected with top toolbar visible, Edit photo panel is closed',
      expectedAction: 'User clicks Edit photo in top toolbar',
      expectedAfterState: 'The left sidebar panel opens displaying Magic Studio / Effects tools including Background Remover, Adjust, and Filters',
      completionCondition: 'The left Edit Photo / Magic Studio sidebar panel opens',
      verificationMethod: 'edit_panel_appearance',
    },
    {
      levelNumber: 3,
      id: 'click_bg_remover',
      title: 'Click Background Remover',
      instruction: 'In the left Edit photo panel, click "BG Remover" (Background Remover).',
      voiceInstruction: 'Click Background Remover in the left panel.',
      targetType: 'BUTTON',
      targetText: 'BG Remover',
      targetDescription: 'The "BG Remover" or "Background Remover" tool button inside the Magic Studio sidebar on the left',
      expectedBeforeState: 'Edit photo panel is open on the left showing tool icons',
      expectedAction: 'User clicks the BG Remover icon',
      expectedAfterState: 'Canva initiates background removal processing or removes background pixels',
      completionCondition: 'Background remover effect is triggered',
      verificationMethod: 'bg_removal_complete',
    },
    {
      levelNumber: 4,
      id: 'verify_removal',
      title: 'Verify background removed',
      instruction: 'Review the canvas to verify the background has been successfully removed.',
      voiceInstruction: 'Verify that the background has been removed.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Processed Canvas',
      targetDescription: 'The canvas area showing the transparent subject',
      expectedBeforeState: 'Background removal in progress or complete',
      expectedAction: 'User observes the result',
      expectedAfterState: 'Subject is isolated with transparent background',
      completionCondition: 'Subject is isolated on the canvas',
      verificationMethod: 'visual_state_change',
    },
  ],
}
