import { Workflow } from '../types/workflow'

export const canvaDownloadDesign: Workflow = {
  id: 'canva_download_design',
  application: 'canva',
  task: 'download_design',
  name: 'Download Design',
  description: 'Export and download your Canva design as PNG/JPG/PDF',
  levels: [
    {
      levelNumber: 1,
      id: 'click_share_button',
      title: 'Click Share button',
      instruction: 'In the top-right header of Canva, click the purple/white "Share" button.',
      voiceInstruction: 'Click the Share button in the top-right corner.',
      targetType: 'BUTTON',
      targetText: 'Share',
      targetDescription: 'The Share button in the top-right header of the Canva editor',
      expectedBeforeState: 'Canva editor active with completed design',
      expectedAction: 'User clicks Share button',
      expectedAfterState: 'The Share dropdown menu opens',
      completionCondition: 'Share dropdown menu is open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'click_download_option',
      title: 'Click Download',
      instruction: 'In the Share menu dropdown, click "Download".',
      voiceInstruction: 'Click Download in the Share menu.',
      targetType: 'BUTTON',
      targetText: 'Download',
      targetDescription: 'The Download action row in the Share menu',
      expectedBeforeState: 'Share dropdown open',
      expectedAction: 'User clicks Download',
      expectedAfterState: 'The Download options dialog opens with File Type choices',
      completionCondition: 'Download export dialog is open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'confirm_download_button',
      title: 'Click Download button',
      instruction: 'Review the file format (PNG/JPG/PDF) and click the purple "Download" button.',
      voiceInstruction: 'Click the purple Download button.',
      targetType: 'BUTTON',
      targetText: 'Download',
      targetDescription: 'The primary purple Download button at the bottom of the export dialog',
      expectedBeforeState: 'Download export options visible',
      expectedAction: 'User clicks Download button',
      expectedAfterState: 'Export progress bar starts and file is downloaded',
      completionCondition: 'Download export process initiated',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_download_complete',
      title: 'Verify file downloaded',
      instruction: 'Verify that the design has downloaded to your Downloads folder.',
      voiceInstruction: 'Verify that your file has downloaded.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Design Canvas',
      targetDescription: 'The Canva design editor showing completed export',
      expectedBeforeState: 'Download started',
      expectedAction: 'User verifies downloaded file',
      expectedAfterState: 'File download complete banner appears',
      completionCondition: 'Export completed successfully',
      verificationMethod: 'visual_state_change',
    },
  ],
}
