import { Workflow } from '../types/workflow'

export const canvaRemoveBackground: Workflow = {
  id: 'canva_remove_background',
  application: 'canva',
  task: 'remove_background',
  name: 'Remove Background',
  description: 'Remove background from an image in Canva',
  levels: [
    {
      levelNumber: 1,
      id: 'select_image',
      title: 'Select the image',
      instruction: 'Click on the image you want to edit on your canvas.',
      voiceInstruction: 'Select the image you want to edit.',
      targetText: 'Image on Canvas',
      targetDescription: 'The main photo or image element on the Canva canvas',
      completionCondition: 'An image is selected with a purple/blue selection border or resize handles around it',
      demoCoordinates: { x: 560, y: 340, width: 400, height: 300 },
    },
    {
      levelNumber: 2,
      id: 'click_edit_photo',
      title: 'Click Edit photo',
      instruction: 'Click "Edit photo" in the top Canva toolbar.',
      voiceInstruction: 'Now click Edit photo.',
      targetText: 'Edit photo',
      targetDescription: 'The "Edit photo" button in the Canva editor toolbar at the top left',
      completionCondition: 'The Edit photo panel or Magic Studio sidebar is open on the left',
      demoCoordinates: { x: 390, y: 56, width: 104, height: 36 },
    },
    {
      levelNumber: 3,
      id: 'click_bg_remover',
      title: 'Click Background Remover',
      instruction: 'In the Edit photo panel on the left, click "BG Remover" (or Background Remover).',
      voiceInstruction: 'Click Background Remover.',
      targetText: 'BG Remover',
      targetDescription: 'The "BG Remover" or "Background Remover" tool icon in the left panel',
      completionCondition: 'Canva begins processing or has removed the background',
      demoCoordinates: { x: 110, y: 205, width: 200, height: 50 },
    },
    {
      levelNumber: 4,
      id: 'verify_removal',
      title: 'Verify background removed',
      instruction: 'Verify that the background has been removed and only the subject remains.',
      voiceInstruction: 'Verify the background is removed.',
      targetText: 'Processed Canvas',
      targetDescription: 'The canvas area showing the transparent background',
      completionCondition: 'The image background is transparent with subject isolated',
      demoCoordinates: { x: 560, y: 340, width: 400, height: 300 },
    },
  ],
}
