import { Workflow } from '../types/workflow'

export const canvaAnimation: Workflow = {
  id: 'canva_add_animation',
  application: 'canva',
  task: 'add_animation',
  name: 'Add Animation',
  description: 'Add animation to an element in Canva',
  levels: [
    {
      levelNumber: 1,
      id: 'select_element',
      title: 'Select text or element',
      instruction: 'Click on the text or graphic element you want to animate on your canvas.',
      voiceInstruction: 'Select the text or element you want to animate.',
      targetText: 'Canvas Element',
      targetDescription: 'A text block or graphic element on the Canva canvas',
      completionCondition: 'An element is selected on canvas with selection handles',
      demoCoordinates: { x: 560, y: 340, width: 320, height: 100 },
    },
    {
      levelNumber: 2,
      id: 'click_animate',
      title: 'Click Animate',
      instruction: 'Click the "Animate" button in the top toolbar.',
      voiceInstruction: 'Now click Animate.',
      targetText: 'Animate',
      targetDescription: 'The "Animate" button in the Canva editor toolbar at the top',
      completionCondition: 'The Animate panel has opened on the left sidebar',
      demoCoordinates: { x: 498, y: 56, width: 80, height: 36 },
    },
    {
      levelNumber: 3,
      id: 'select_animation_style',
      title: 'Select an animation',
      instruction: 'Choose an animation style from the left panel (e.g. Fade, Rise, Pop, Breathe).',
      voiceInstruction: 'Select an animation style from the left panel.',
      targetText: 'Animation Style',
      targetDescription: 'An animation style option card in the left animate panel',
      completionCondition: 'An animation style is highlighted and applied to the element',
      demoCoordinates: { x: 110, y: 240, width: 190, height: 50 },
    },
    {
      levelNumber: 4,
      id: 'verify_animation',
      title: 'Verify animation applied',
      instruction: 'Preview the animation using the play button or confirm it is active.',
      voiceInstruction: 'Verify your animation is applied.',
      targetText: 'Preview',
      targetDescription: 'The preview control or animated element',
      completionCondition: 'The animation has been applied to the element',
      demoCoordinates: { x: 560, y: 340, width: 320, height: 100 },
    },
  ],
}
