import { Workflow } from '../types/workflow'

export const canvaAddText: Workflow = {
  id: 'canva_add_text',
  application: 'canva',
  task: 'add_text',
  name: 'Add Text to Design',
  description: 'Add a new text box or heading to your Canva design',
  levels: [
    {
      levelNumber: 1,
      id: 'click_text_tool',
      title: 'Click Text tool',
      instruction: 'In the left Canva sidebar, click on the "Text" tool (or press T on your keyboard).',
      voiceInstruction: 'Click the Text tool in the left sidebar.',
      targetType: 'BUTTON',
      targetText: 'Text',
      targetDescription: 'The Text navigation icon in the left Canva tool sidebar',
      expectedBeforeState: 'Canva design open in editor',
      expectedAction: 'User clicks Text tool icon',
      expectedAfterState: 'The Text side panel opens showing text box choices and typography presets',
      completionCondition: 'Text tools panel is open on the left',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'add_text_box',
      title: 'Click Add a text box',
      instruction: 'In the left panel, click "Add a text box" (or "Add a heading").',
      voiceInstruction: 'Click Add a text box in the panel.',
      targetType: 'BUTTON',
      targetText: 'Add a text box',
      targetDescription: 'The "Add a text box" button or heading template in the Text panel',
      expectedBeforeState: 'Text panel open',
      expectedAction: 'User clicks Add a text box',
      expectedAfterState: 'A new editable text element appears on the central canvas with a selection box',
      completionCondition: 'New text element appears on design canvas',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'type_content',
      title: 'Type your message',
      instruction: 'Type your desired message into the active text box on the canvas.',
      voiceInstruction: 'Type your text inside the text box on the canvas.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Text on Canvas',
      targetDescription: 'The newly placed text box on the design canvas',
      expectedBeforeState: 'Text box active with default placeholder',
      expectedAction: 'User types custom text',
      expectedAfterState: 'Canvas text displays typed message',
      completionCondition: 'User typed text into the canvas element',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_text_element',
      title: 'Verify text visible',
      instruction: 'Click outside or review the canvas to verify your text is rendered cleanly.',
      voiceInstruction: 'Verify that your text is rendered on the canvas.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Text on Canvas',
      targetDescription: 'The rendered text element on the Canva canvas',
      expectedBeforeState: 'Text entered',
      expectedAction: 'User reviews design canvas',
      expectedAfterState: 'Text object is placed and readable on canvas',
      completionCondition: 'Text element is confirmed on canvas',
      verificationMethod: 'visual_state_change',
    },
  ],
}
