import { Workflow } from '../types/workflow'

export const chromeHistory: Workflow = {
  id: 'chrome_history',
  application: 'chrome',
  task: 'clear_history',
  name: 'Clear Browsing History',
  description: 'Open Chrome browsing history and clear cached data and cookies',
  levels: [
    {
      levelNumber: 1,
      id: 'open_history_menu',
      title: 'Open History Menu',
      instruction: 'Click the three-dot menu, hover over "History", and click "History" (or press Ctrl+H).',
      voiceInstruction: 'Open History from the Chrome menu or press Control H.',
      targetType: 'BUTTON',
      targetText: 'Customize and control Google Chrome',
      targetDescription: 'The three-dot menu button to access browser history',
      expectedBeforeState: 'Chrome window open',
      expectedAction: 'User navigates to History',
      expectedAfterState: 'History page open (chrome://history)',
      completionCondition: 'History page is loaded',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'click_clear_browsing_data',
      title: 'Click Clear Browsing Data',
      instruction: 'In the left sidebar of the History page, click "Clear browsing data".',
      voiceInstruction: 'Click Clear browsing data in the left sidebar.',
      targetType: 'BUTTON',
      targetText: 'Clear browsing data',
      targetDescription: 'The Clear browsing data navigation button in Chrome history',
      expectedBeforeState: 'History page open',
      expectedAction: 'User clicks Clear browsing data',
      expectedAfterState: 'Clear browsing data modal dialog appears',
      completionCondition: 'Clear browsing data dialog open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'select_time_range',
      title: 'Select Time Range',
      instruction: 'In the popup, choose a Time range (e.g. "Last hour", "All time") and select checkboxes for history, cookies, or cache.',
      voiceInstruction: 'Choose your desired time range and data types.',
      targetType: 'INPUT',
      targetText: 'Time range',
      targetDescription: 'The time range dropdown selector in the clear data modal',
      expectedBeforeState: 'Clear browsing data modal active',
      expectedAction: 'User chooses time range and options',
      expectedAfterState: 'Options selected',
      completionCondition: 'Time range selected',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'confirm_clear_data',
      title: 'Click Clear Data',
      instruction: 'Click the blue "Delete data" or "Clear data" button to confirm.',
      voiceInstruction: 'Click the Clear data button to finalize.',
      targetType: 'BUTTON',
      targetText: 'Clear data',
      targetDescription: 'The primary confirmation button to delete browsing data',
      expectedBeforeState: 'Time range and items configured',
      expectedAction: 'User clicks Clear data',
      expectedAfterState: 'Dialog closes after clearing data',
      completionCondition: 'Browsing data cleared successfully',
      verificationMethod: 'visual_state_change',
    },
  ],
}
