import { Workflow } from '../types/workflow'

export const chromeDownloads: Workflow = {
  id: 'chrome_downloads',
  application: 'chrome',
  task: 'view_downloads',
  name: 'View Download History',
  description: 'Access and manage downloaded files in Google Chrome',
  levels: [
    {
      levelNumber: 1,
      id: 'open_chrome_menu',
      title: 'Click Three-Dot Menu',
      instruction: 'Click the three-dot "Customize and control" menu button in the top-right corner of Chrome.',
      voiceInstruction: 'Click the three dots menu at the top right.',
      targetType: 'BUTTON',
      targetText: 'Customize and control Google Chrome',
      targetDescription: 'The three-dot options menu icon in top right of Chrome',
      expectedBeforeState: 'Chrome window active',
      expectedAction: 'User clicks three-dot menu',
      expectedAfterState: 'Chrome main menu dropdown opens',
      completionCondition: 'Chrome menu dropdown is visible',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'click_downloads_item',
      title: 'Click Downloads',
      instruction: 'In the dropdown menu, click "Downloads" (or press Ctrl+J directly).',
      voiceInstruction: 'Click Downloads or press Control J.',
      targetType: 'MENU_ITEM',
      targetText: 'Downloads',
      targetDescription: 'The Downloads menu item in the Chrome options list',
      expectedBeforeState: 'Chrome menu open',
      expectedAction: 'User clicks Downloads',
      expectedAfterState: 'Downloads tab opens displaying recently downloaded files',
      completionCondition: 'Downloads page is displayed',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'locate_download_file',
      title: 'Locate Downloaded File',
      instruction: 'Browse the downloads list to find the file you downloaded.',
      voiceInstruction: 'Find your downloaded file in the list.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Downloads List',
      targetDescription: 'The list of downloaded files on chrome://downloads',
      expectedBeforeState: 'Downloads page visible',
      expectedAction: 'User identifies file card',
      expectedAfterState: 'File card located',
      completionCondition: 'Target file card is visible',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'open_file_or_folder',
      title: 'Open File or Show in Folder',
      instruction: 'Click the file name to open it, or click "Show in folder" to view it in File Explorer.',
      voiceInstruction: 'Click the file or Show in folder to open it.',
      targetType: 'BUTTON',
      targetText: 'Show in folder',
      targetDescription: 'The button/link to reveal file in Windows File Explorer',
      expectedBeforeState: 'File card in downloads list',
      expectedAction: 'User clicks file link or Show in folder',
      expectedAfterState: 'File opens in default app or File Explorer folder opens',
      completionCondition: 'File accessed successfully',
      verificationMethod: 'visual_state_change',
    },
  ],
}
