import { Workflow } from '../types/workflow'

export const chromeBookmarkPage: Workflow = {
  id: 'chrome_bookmark_page',
  application: 'chrome',
  task: 'bookmark_page',
  name: 'Bookmark Current Web Page',
  description: 'Add the active web page to Google Chrome bookmarks for quick access',
  levels: [
    {
      levelNumber: 1,
      id: 'navigate_target_page',
      title: 'Navigate to target page',
      instruction: 'Ensure the web page you wish to bookmark is currently open in Chrome.',
      voiceInstruction: 'Make sure the web page you want to bookmark is open.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Web Content Area',
      targetDescription: 'The active webpage viewport in Chrome',
      expectedBeforeState: 'Target web page displayed',
      expectedAction: 'User verifies page is loaded',
      expectedAfterState: 'Ready to bookmark',
      completionCondition: 'Active web page confirmed',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'click_bookmark_star',
      title: 'Click Bookmark Star',
      instruction: 'Click the star icon on the right side of the address bar (or press Ctrl+D).',
      voiceInstruction: 'Click the star icon in the address bar to bookmark this page.',
      targetType: 'BUTTON',
      targetText: 'Bookmark this tab',
      targetDescription: 'The star bookmark icon in the Chrome address bar',
      expectedBeforeState: 'Web page open',
      expectedAction: 'User clicks star icon or presses Ctrl+D',
      expectedAfterState: 'Bookmark dialog bubble appears',
      completionCondition: 'Bookmark dialog is open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'edit_bookmark_name',
      title: 'Edit Bookmark Details',
      instruction: 'In the popup dialog, customize the bookmark Name or choose a Folder.',
      voiceInstruction: 'Customize the bookmark name or folder if desired.',
      targetType: 'INPUT',
      targetText: 'Name',
      targetDescription: 'The Name input field in the Bookmark Added popup',
      expectedBeforeState: 'Bookmark dialog visible',
      expectedAction: 'User edits name or selects folder',
      expectedAfterState: 'Bookmark settings configured',
      completionCondition: 'Bookmark details entered',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'click_done_bookmark',
      title: 'Click Done to Save',
      instruction: 'Click "Done" to finalize and save the bookmark.',
      voiceInstruction: 'Click Done to save your bookmark.',
      targetType: 'BUTTON',
      targetText: 'Done',
      targetDescription: 'The Done button to confirm bookmark creation',
      expectedBeforeState: 'Bookmark dialog open',
      expectedAction: 'User clicks Done button',
      expectedAfterState: 'Dialog closes and star turns solid blue',
      completionCondition: 'Bookmark saved and dialog dismissed',
      verificationMethod: 'visual_state_change',
    },
  ],
}
