import { Workflow } from '../types/workflow'

export const chromeFindInPage: Workflow = {
  id: 'chrome_find_in_page',
  application: 'chrome',
  task: 'find_in_page',
  name: 'Find Text in Web Page',
  description: 'Search for specific words or phrases inside the current web page',
  levels: [
    {
      levelNumber: 1,
      id: 'open_find_bar',
      title: 'Open Find Bar',
      instruction: 'Press Ctrl+F (or click the three-dot menu in top right and choose "Find and edit" → "Find...").',
      voiceInstruction: 'Press Control F to open the Find in page bar.',
      targetType: 'BUTTON',
      targetText: 'Customize and control Google Chrome',
      targetDescription: 'The Chrome three-dot menu button or Ctrl+F trigger',
      expectedBeforeState: 'Web page active',
      expectedAction: 'User triggers Find command',
      expectedAfterState: 'Find bar appears at top right',
      completionCondition: 'Find in page bar is visible',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'type_search_term',
      title: 'Type search keyword',
      instruction: 'Type the word or phrase you want to search for in the Find box.',
      voiceInstruction: 'Type the search term in the Find bar.',
      targetType: 'INPUT',
      targetText: 'Find in page',
      targetDescription: 'The text input field inside the Chrome Find toolbar',
      expectedBeforeState: 'Find bar open',
      expectedAction: 'User inputs search keywords',
      expectedAfterState: 'Matching occurrences highlighted on the page with counter shown',
      completionCondition: 'Keyword entered in find input',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'navigate_results',
      title: 'Navigate matches with arrows',
      instruction: 'Click the Up or Down arrow buttons next to the Find box (or press Enter) to jump between matches.',
      voiceInstruction: 'Use the arrow buttons or press Enter to step through matches.',
      targetType: 'BUTTON',
      targetText: 'Next',
      targetDescription: 'The down arrow button in the Find bar to jump to next occurrence',
      expectedBeforeState: 'Matches highlighted on webpage',
      expectedAction: 'User clicks Next arrow or presses Enter',
      expectedAfterState: 'Viewport scrolls to highlight active match',
      completionCondition: 'Jumped to next match occurrence',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'close_find_bar',
      title: 'Close Find Bar',
      instruction: 'When finished reviewing matches, press Esc or click "X" to close the Find bar.',
      voiceInstruction: 'Press Escape or click X to close the Find bar.',
      targetType: 'BUTTON',
      targetText: 'Close',
      targetDescription: 'The X button on the right side of the Find bar',
      expectedBeforeState: 'Find bar open',
      expectedAction: 'User presses Esc or clicks X',
      expectedAfterState: 'Find bar dismissed and page highlights cleared',
      completionCondition: 'Find bar is closed',
      verificationMethod: 'visual_state_change',
    },
  ],
}
