import { Workflow } from '../types/workflow'

export const chromeOpenNewTab: Workflow = {
  id: 'chrome_open_new_tab',
  application: 'chrome',
  task: 'open_new_tab',
  name: 'Open New Tab & Navigate',
  description: 'Open a new browsing tab in Google Chrome and navigate to a URL',
  levels: [
    {
      levelNumber: 1,
      id: 'click_new_tab',
      title: 'Click New Tab Button',
      instruction: 'Click the "+" new tab button next to the last tab at the top of Chrome.',
      voiceInstruction: 'Click the plus icon to open a new tab.',
      targetType: 'BUTTON',
      targetText: 'New Tab',
      targetDescription: 'The plus icon button to create a new tab in Chrome',
      expectedBeforeState: 'Chrome browser window open',
      expectedAction: 'User clicks New Tab button or presses Ctrl+T',
      expectedAfterState: 'New tab created and address bar focused',
      completionCondition: 'New tab opened in Chrome',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'focus_address_bar',
      title: 'Focus Address Bar',
      instruction: 'Click into the address and search bar (Omnibox) at the top of the browser.',
      voiceInstruction: 'Click the address bar to prepare typing.',
      targetType: 'INPUT',
      targetText: 'Address and search bar',
      targetDescription: 'The Chrome omnibox / URL address bar',
      expectedBeforeState: 'New tab active',
      expectedAction: 'User focuses address bar',
      expectedAfterState: 'Cursor active in address bar',
      completionCondition: 'Address bar is focused',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'type_and_enter',
      title: 'Type URL & Press Enter',
      instruction: 'Type the website URL or search keywords and press Enter on your keyboard.',
      voiceInstruction: 'Type your web address and press Enter to navigate.',
      targetType: 'INPUT',
      targetText: 'Address and search bar',
      targetDescription: 'Chrome URL bar with entered query',
      expectedBeforeState: 'Query entered in address bar',
      expectedAction: 'User presses Enter to navigate',
      expectedAfterState: 'Browser initiates page request',
      completionCondition: 'Navigation requested',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_page_loaded',
      title: 'Verify Page Loaded',
      instruction: 'Verify that the target website has loaded successfully in the new tab.',
      voiceInstruction: 'Verify that the web page has loaded.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Web Content Area',
      targetDescription: 'The main web browser viewport displaying the loaded page',
      expectedBeforeState: 'Page rendering',
      expectedAction: 'Page finishes rendering',
      expectedAfterState: 'Target web page fully displayed',
      completionCondition: 'Page content is visible in tab',
      verificationMethod: 'visual_state_change',
    },
  ],
}
