import { Workflow } from '../types/workflow'

export const excelFreezeRow: Workflow = {
  id: 'excel_freeze_row',
  application: 'excel',
  task: 'freeze_row',
  name: 'Freeze Top Row',
  description: 'Freeze the top header row so it stays visible while scrolling in Microsoft Excel',
  levels: [
    {
      levelNumber: 1,
      id: 'select_worksheet',
      title: 'Click in worksheet',
      instruction: 'Click anywhere inside your Excel worksheet table.',
      voiceInstruction: 'Click inside your Excel worksheet.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Data Cells Range',
      targetDescription: 'The active worksheet data area',
      expectedBeforeState: 'Excel spreadsheet open',
      expectedAction: 'User clicks inside sheet',
      expectedAfterState: 'Worksheet is active',
      completionCondition: 'Worksheet is active and focused',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'open_view_tab',
      title: 'Click View tab',
      instruction: 'In the top Excel ribbon, click on the "View" tab.',
      voiceInstruction: 'Click the View tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'View',
      targetDescription: 'The View tab in the Microsoft Excel top ribbon menu',
      expectedBeforeState: 'Worksheet active',
      expectedAction: 'User clicks View tab',
      expectedAfterState: 'View ribbon is active showing Window and Freeze Panes tools',
      completionCondition: 'View tab in Excel ribbon is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'click_freeze_panes_menu',
      title: 'Click Freeze Panes',
      instruction: 'In the Window group on the View ribbon, click "Freeze Panes".',
      voiceInstruction: 'Click Freeze Panes in the Window group.',
      targetType: 'BUTTON',
      targetText: 'Freeze Panes',
      targetDescription: 'The Freeze Panes dropdown button in the Excel View ribbon',
      expectedBeforeState: 'View ribbon visible',
      expectedAction: 'User clicks Freeze Panes dropdown',
      expectedAfterState: 'Freeze Panes menu opens with Top Row and First Column options',
      completionCondition: 'Freeze Panes menu is open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'select_freeze_top_row',
      title: 'Click Freeze Top Row',
      instruction: 'In the dropdown menu, click "Freeze Top Row".',
      voiceInstruction: 'Click Freeze Top Row to lock your headers.',
      targetType: 'BUTTON',
      targetText: 'Freeze Panes',
      targetDescription: 'The "Freeze Top Row" option in the Freeze Panes dropdown',
      expectedBeforeState: 'Freeze Panes dropdown open',
      expectedAction: 'User clicks Freeze Top Row',
      expectedAfterState: 'A thin gray freeze line appears under row 1 and it stays pinned',
      completionCondition: 'Top row is locked and frozen',
      verificationMethod: 'visual_state_change',
    },
  ],
}
