import { Workflow } from '../types/workflow'

export const excelAutoSum: Workflow = {
  id: 'excel_autosum',
  application: 'excel',
  task: 'autosum',
  name: 'Calculate AutoSum',
  description: 'Automatically sum a column or row of numbers in Microsoft Excel',
  levels: [
    {
      levelNumber: 1,
      id: 'select_target_cell',
      title: 'Select sum cell',
      instruction: 'Click on the empty cell directly below or to the right of your numbers.',
      voiceInstruction: 'Click the empty cell below your numbers where the sum should go.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Data Cells Range',
      targetDescription: 'The empty cell at the bottom of the number column',
      expectedBeforeState: 'Column of numbers entered in worksheet',
      expectedAction: 'User selects destination cell',
      expectedAfterState: 'Active cell border is on the target cell',
      completionCondition: 'Destination cell selected in worksheet',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'open_home_tab',
      title: 'Click Home tab',
      instruction: 'In the top Excel ribbon, click on the "Home" tab.',
      voiceInstruction: 'Click the Home tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'Home',
      targetDescription: 'The Home tab in the Microsoft Excel top ribbon menu',
      expectedBeforeState: 'Target cell selected',
      expectedAction: 'User clicks Home tab',
      expectedAfterState: 'Home ribbon is active showing the Editing group on the far right',
      completionCondition: 'Home tab in Excel ribbon is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'click_autosum_button',
      title: 'Click AutoSum (Σ)',
      instruction: 'In the Editing group on the right of the Home ribbon, click "AutoSum" (Σ).',
      voiceInstruction: 'Click AutoSum in the Editing group on the right.',
      targetType: 'BUTTON',
      targetText: 'AutoSum',
      targetDescription: 'The AutoSum (Σ) button in the Excel Home ribbon Editing group',
      expectedBeforeState: 'Home ribbon active with AutoSum button visible',
      expectedAction: 'User clicks AutoSum button',
      expectedAfterState: '=SUM(...) formula is inserted into the active cell',
      completionCondition: 'AutoSum formula is placed in cell',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'press_enter_to_confirm',
      title: 'Press Enter to calculate',
      instruction: 'Press the Enter key on your keyboard to calculate and lock in the total sum.',
      voiceInstruction: 'Press Enter on your keyboard to calculate the sum.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Data Cells Range',
      targetDescription: 'The cell showing the calculated sum total',
      expectedBeforeState: '=SUM formula in edit mode',
      expectedAction: 'User presses Enter key',
      expectedAfterState: 'Cell displays the numeric calculated total',
      completionCondition: 'Sum calculation is displayed in cell',
      verificationMethod: 'visual_state_change',
    },
  ],
}
