import { Workflow } from '../types/workflow'

export const excelChart: Workflow = {
  id: 'excel_create_chart',
  application: 'excel',
  task: 'create_chart',
  name: 'Create Chart',
  description: 'Create a chart from selected data in Microsoft Excel',
  levels: [
    {
      levelNumber: 1,
      id: 'select_data',
      title: 'Select data range',
      instruction: 'Click and drag to select the cells containing your data (including headers).',
      voiceInstruction: 'Select your data range in Excel.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Data Cells',
      targetDescription: 'The spreadsheet grid containing the data table',
      expectedBeforeState: 'Cells not yet selected',
      expectedAction: 'User highlights a block of cells in Excel',
      expectedAfterState: 'Selection box surrounds the active data range',
      completionCondition: 'Data cells are highlighted in Excel',
      verificationMethod: 'excel_chart',
    },
    {
      levelNumber: 2,
      id: 'open_insert_tab',
      title: 'Open Insert tab',
      instruction: 'Click on the "Insert" tab in the top Excel ribbon.',
      voiceInstruction: 'Click on the Insert tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'Insert',
      targetDescription: 'The "Insert" tab in the Microsoft Excel top ribbon menu',
      expectedBeforeState: 'Home or another ribbon tab is active',
      expectedAction: 'User clicks Insert tab',
      expectedAfterState: 'Insert ribbon tab is active showing charts group',
      completionCondition: 'Insert tab in Excel ribbon is selected',
      verificationMethod: 'excel_insert_tab',
    },
    {
      levelNumber: 3,
      id: 'select_chart_type',
      title: 'Choose chart type',
      instruction: 'In the Charts group, click "Recommended Charts" or choose a Column/Bar chart.',
      voiceInstruction: 'Click Recommended Charts or choose a chart type.',
      targetType: 'BUTTON',
      targetText: 'Recommended Charts',
      targetDescription: 'The "Recommended Charts" or Column/Bar Chart icon in the Insert ribbon',
      expectedBeforeState: 'Insert ribbon visible with chart buttons',
      expectedAction: 'User clicks chart type icon',
      expectedAfterState: 'Chart dialog or chart object is placed on the sheet',
      completionCondition: 'Chart is inserted into the worksheet',
      verificationMethod: 'excel_chart',
    },
    {
      levelNumber: 4,
      id: 'verify_chart',
      title: 'Verify chart created',
      instruction: 'Verify that the chart is inserted and displays your data accurately.',
      voiceInstruction: 'Verify that your chart is created.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Chart on Worksheet',
      targetDescription: 'The inserted chart object on the Excel sheet',
      expectedBeforeState: 'Chart created',
      expectedAction: 'User verifies chart appearance',
      expectedAfterState: 'Chart object with legend and bars/columns is active',
      completionCondition: 'Chart element exists on worksheet',
      verificationMethod: 'excel_chart',
    },
  ],
}
