import { Workflow } from '../types/workflow'

export const excelChart: Workflow = {
  id: 'excel_create_chart',
  application: 'excel',
  task: 'create_chart',
  name: 'Create Chart',
  description: 'Create a chart from data in Microsoft Excel',
  levels: [
    {
      levelNumber: 1,
      id: 'select_data',
      title: 'Select data range',
      instruction: 'Click and drag across the cells containing your data table and headers.',
      voiceInstruction: 'Select the relevant data in your spreadsheet.',
      targetText: 'Data Cells',
      targetDescription: 'The cells containing the data table to be charted in Excel',
      completionCondition: 'A range of cells is highlighted with an active selection outline',
      demoCoordinates: { x: 80, y: 190, width: 320, height: 180 },
    },
    {
      levelNumber: 2,
      id: 'open_insert_tab',
      title: 'Open Insert tab',
      instruction: 'Click the "Insert" tab in the top Excel ribbon.',
      voiceInstruction: 'Open the Insert tab in the top ribbon.',
      targetText: 'Insert Tab',
      targetDescription: 'The "Insert" tab button in the Excel ribbon toolbar',
      completionCondition: 'The Insert ribbon is active displaying chart options',
      demoCoordinates: { x: 202, y: 52, width: 60, height: 24 },
    },
    {
      levelNumber: 3,
      id: 'select_chart_type',
      title: 'Select chart type',
      instruction: 'In the Charts group of the ribbon, click "Insert Column or Bar Chart" (or Recommended Charts).',
      voiceInstruction: 'Select a chart type from the ribbon.',
      targetText: 'Chart Type',
      targetDescription: 'A chart type icon button in the Charts group of the Excel ribbon',
      completionCondition: 'A chart object is inserted into the worksheet',
      demoCoordinates: { x: 380, y: 62, width: 60, height: 48 },
    },
    {
      levelNumber: 4,
      id: 'verify_chart',
      title: 'Verify chart created',
      instruction: 'Confirm the chart has appeared on your worksheet. You can move or format it.',
      voiceInstruction: 'Verify your chart appears on the spreadsheet.',
      targetText: 'Chart Object',
      targetDescription: 'The chart visual object rendered on the Excel worksheet',
      completionCondition: 'A chart is visible and rendered in the Excel worksheet',
      demoCoordinates: { x: 450, y: 220, width: 420, height: 280 },
    },
  ],
}
