import { Workflow } from '../types/workflow'

export const excelFormatCells: Workflow = {
  id: 'excel_format_cells',
  application: 'excel',
  task: 'format_cells',
  name: 'Format Cells (Bold & Highlight)',
  description: 'Apply bold formatting and fill color to selected cells in Microsoft Excel',
  levels: [
    {
      levelNumber: 1,
      id: 'select_cells_to_format',
      title: 'Select cells',
      instruction: 'Click and drag across the cells or column header you wish to format.',
      voiceInstruction: 'Select the cells you want to format in Excel.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Data Cells Range',
      targetDescription: 'The Excel worksheet grid cells you wish to format',
      expectedBeforeState: 'Excel worksheet open with data',
      expectedAction: 'User highlights a cell range',
      expectedAfterState: 'Selected cells are highlighted with the Excel selection outline',
      completionCondition: 'Cell range is selected in worksheet',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'open_home_tab',
      title: 'Click Home tab',
      instruction: 'In the top Excel ribbon, click on the "Home" tab.',
      voiceInstruction: 'Click the Home tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'Home',
      targetDescription: 'The Home tab in the Microsoft Excel top ribbon menu',
      expectedBeforeState: 'Cells selected in worksheet',
      expectedAction: 'User clicks Home tab',
      expectedAfterState: 'Home ribbon is active showing Font and Alignment groups',
      completionCondition: 'Home tab in Excel ribbon is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'apply_bold',
      title: 'Click Bold (B)',
      instruction: 'In the Font group on the Home ribbon, click the "Bold" (B) button.',
      voiceInstruction: 'Click the Bold button in the Font group.',
      targetType: 'BUTTON',
      targetText: 'Bold',
      targetDescription: 'The Bold (B) formatting button in the Excel Home ribbon',
      expectedBeforeState: 'Home tab active with Bold button visible',
      expectedAction: 'User clicks Bold button',
      expectedAfterState: 'Selected cell contents become bold',
      completionCondition: 'Bold formatting is applied to selected cells',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_formatting',
      title: 'Verify formatted cells',
      instruction: 'Verify that the selected cells now display with bold typography.',
      voiceInstruction: 'Verify that your cells are formatted as bold.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Data Cells Range',
      targetDescription: 'The styled cells on the worksheet grid',
      expectedBeforeState: 'Bold applied',
      expectedAction: 'User verifies formatted text',
      expectedAfterState: 'Cell contents are bolded',
      completionCondition: 'Cell formatting change confirmed',
      verificationMethod: 'visual_state_change',
    },
  ],
}
