import { Workflow } from '../types/workflow'

export const gmailReply: Workflow = {
  id: 'gmail_reply',
  application: 'chrome_gmail',
  task: 'reply_email',
  name: 'Reply to Email in Gmail',
  description: 'Open an existing conversation and send a reply message',
  levels: [
    {
      levelNumber: 1,
      id: 'open_email_thread',
      title: 'Open Email Conversation',
      instruction: 'Click on the email thread in your inbox list to open and view the conversation.',
      voiceInstruction: 'Click the email conversation to open it.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Inbox List',
      targetDescription: 'The email conversation row in the Gmail inbox',
      expectedBeforeState: 'Gmail inbox displayed',
      expectedAction: 'User clicks email row',
      expectedAfterState: 'Email message thread is opened',
      completionCondition: 'Email message thread open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'click_reply_button',
      title: 'Click Reply',
      instruction: 'Scroll to the bottom of the email and click the "Reply" button (or the left curved arrow icon).',
      voiceInstruction: 'Click the Reply button below the message.',
      targetType: 'BUTTON',
      targetText: 'Reply',
      targetDescription: 'The Reply action button at the bottom of the email thread',
      expectedBeforeState: 'Email thread view active',
      expectedAction: 'User clicks Reply',
      expectedAfterState: 'Inline reply editor opens with recipient pre-filled',
      completionCondition: 'Reply editor active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'type_reply_message',
      title: 'Type Reply Message',
      instruction: 'Type your reply message in the response text box.',
      voiceInstruction: 'Type your reply message.',
      targetType: 'INPUT',
      targetText: 'Message Body',
      targetDescription: 'The inline reply rich text box',
      expectedBeforeState: 'Reply editor open',
      expectedAction: 'User types reply text',
      expectedAfterState: 'Reply message drafted',
      completionCondition: 'Reply text entered',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'send_reply',
      title: 'Click Send',
      instruction: 'Click the blue "Send" button to dispatch your reply.',
      voiceInstruction: 'Click the Send button to send your reply.',
      targetType: 'BUTTON',
      targetText: 'Send',
      targetDescription: 'The Send button for the inline reply box',
      expectedBeforeState: 'Reply draft ready',
      expectedAction: 'User clicks Send',
      expectedAfterState: 'Reply added to thread and "Message sent" confirmation shown',
      completionCondition: 'Reply email sent successfully',
      verificationMethod: 'visual_state_change',
    },
  ],
}
