import { Workflow } from '../types/workflow'

export const gmailCompose: Workflow = {
  id: 'gmail_compose',
  application: 'chrome_gmail',
  task: 'compose_email',
  name: 'Compose New Email in Gmail',
  description: 'Create, draft, and send a new email message in Gmail',
  levels: [
    {
      levelNumber: 1,
      id: 'click_compose',
      title: 'Click Compose Button',
      instruction: 'In the top-left corner of Gmail, click the large "Compose" button (with a pencil icon).',
      voiceInstruction: 'Click the Compose button in the top left.',
      targetType: 'BUTTON',
      targetText: 'Compose',
      targetDescription: 'The Compose email button in Gmail left navigation',
      expectedBeforeState: 'Gmail inbox view active',
      expectedAction: 'User clicks Compose button',
      expectedAfterState: 'New Message compose window opens in bottom right',
      completionCondition: 'Compose window is open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'enter_recipients',
      title: 'Enter Recipients (To)',
      instruction: 'Click the "To" field and type the recipient email address.',
      voiceInstruction: 'Type the recipient email address in the To field.',
      targetType: 'INPUT',
      targetText: 'To',
      targetDescription: 'The recipient To input field in the compose box',
      expectedBeforeState: 'Compose box open',
      expectedAction: 'User enters email address',
      expectedAfterState: 'Recipient chip added',
      completionCondition: 'Recipient email entered',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'enter_subject_and_body',
      title: 'Enter Subject & Message Body',
      instruction: 'Type your email subject in the "Subject" line, then click into the message area below and type your email content.',
      voiceInstruction: 'Type the subject and your message content.',
      targetType: 'INPUT',
      targetText: 'Subject',
      targetDescription: 'The Subject line and message body text area in Gmail',
      expectedBeforeState: 'Recipient added',
      expectedAction: 'User types subject and message text',
      expectedAfterState: 'Subject and message populated',
      completionCondition: 'Subject and message text entered',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'click_send',
      title: 'Click Send Button',
      instruction: 'Click the blue "Send" button (or press Ctrl+Enter) to send the email.',
      voiceInstruction: 'Click the Send button or press Control Enter to send.',
      targetType: 'BUTTON',
      targetText: 'Send',
      targetDescription: 'The blue Send button at the bottom of the compose window',
      expectedBeforeState: 'Completed email draft ready',
      expectedAction: 'User clicks Send',
      expectedAfterState: 'Compose window closes and "Message sent" toast notification appears',
      completionCondition: 'Email is sent successfully',
      verificationMethod: 'visual_state_change',
    },
  ],
}
