import { Workflow } from '../types/workflow'

export const notepadFindReplace: Workflow = {
  id: 'notepad_find_replace',
  application: 'notepad',
  task: 'find_replace',
  name: 'Find and Replace Text',
  description: 'Find and replace text in Windows Notepad',
  levels: [
    {
      levelNumber: 1,
      id: 'focus_editor',
      title: 'Click in document',
      instruction: 'Click inside the text editing area of Notepad.',
      voiceInstruction: 'Click inside the Notepad document area.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Text Area',
      targetDescription: 'The text editing area of Windows Notepad',
      expectedBeforeState: 'Notepad window open',
      expectedAction: 'User clicks inside text area',
      expectedAfterState: 'Text cursor is active in Notepad',
      completionCondition: 'Notepad text area is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'open_replace_dialog',
      title: 'Open Replace dialog',
      instruction: 'Click the "Edit" menu and select "Replace" (or press Ctrl+H).',
      voiceInstruction: 'Click the Edit menu and choose Replace.',
      targetType: 'BUTTON',
      targetText: 'Edit',
      targetDescription: 'The Edit menu in the top menu bar of Notepad',
      expectedBeforeState: 'Text area active',
      expectedAction: 'User opens Replace dialog',
      expectedAfterState: 'Find and Replace dialog is open on screen',
      completionCondition: 'Replace dialog is open in Notepad',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'enter_search_terms',
      title: 'Enter search terms',
      instruction: 'Type your search term and the replacement text in the dialog.',
      voiceInstruction: 'Type the search term and the replacement text.',
      targetType: 'BUTTON',
      targetText: 'Replace',
      targetDescription: 'The Replace dialog input fields and action buttons',
      expectedBeforeState: 'Replace dialog open',
      expectedAction: 'User types search terms',
      expectedAfterState: 'Search and replace terms are filled in',
      completionCondition: 'Search terms are entered',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'click_replace_all',
      title: 'Click Replace All',
      instruction: 'Click "Replace All" to replace all occurrences across the document.',
      voiceInstruction: 'Click Replace All to update your document.',
      targetType: 'BUTTON',
      targetText: 'Replace',
      targetDescription: 'The Replace All button in the Notepad Replace dialog',
      expectedBeforeState: 'Search terms filled in',
      expectedAction: 'User clicks Replace All',
      expectedAfterState: 'All matched text occurrences are replaced',
      completionCondition: 'Replace operation completed in Notepad',
      verificationMethod: 'visual_state_change',
    },
  ],
}
