import { Workflow } from '../types/workflow'

export const notepadSaveAs: Workflow = {
  id: 'notepad_save_as',
  application: 'notepad',
  task: 'save_as',
  name: 'Save File As',
  description: 'Save your text file with a new name in Windows Notepad',
  levels: [
    {
      levelNumber: 1,
      id: 'open_file_menu',
      title: 'Click File menu',
      instruction: 'In the top menu bar of Notepad, click on "File".',
      voiceInstruction: 'Click the File menu in the top bar.',
      targetType: 'BUTTON',
      targetText: 'File',
      targetDescription: 'The File menu in the top menu bar of Notepad',
      expectedBeforeState: 'Notepad open with document text',
      expectedAction: 'User clicks File menu',
      expectedAfterState: 'File menu dropdown opens',
      completionCondition: 'File menu is open in Notepad',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'click_save_as',
      title: 'Click Save As',
      instruction: 'In the File menu dropdown, click "Save As" (or press Ctrl+Shift+S).',
      voiceInstruction: 'Click Save As in the menu.',
      targetType: 'BUTTON',
      targetText: 'Save',
      targetDescription: 'The Save As option in the Notepad File menu',
      expectedBeforeState: 'File menu open',
      expectedAction: 'User clicks Save As',
      expectedAfterState: 'Windows file Save As dialog opens',
      completionCondition: 'Save As dialog is open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'enter_file_name',
      title: 'Enter file name',
      instruction: 'Type the name for your file in the "File name" box.',
      voiceInstruction: 'Type your file name in the Save As dialog.',
      targetType: 'BUTTON',
      targetText: 'Save',
      targetDescription: 'The File name text input field in the Windows file save dialog',
      expectedBeforeState: 'Save As dialog open',
      expectedAction: 'User types file name',
      expectedAfterState: 'File name is entered',
      completionCondition: 'File name is entered in dialog',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'click_save_button',
      title: 'Click Save',
      instruction: 'Click the "Save" button to save your document.',
      voiceInstruction: 'Click Save to finish saving your file.',
      targetType: 'BUTTON',
      targetText: 'Save',
      targetDescription: 'The Save button in the Windows file dialog',
      expectedBeforeState: 'File name entered',
      expectedAction: 'User clicks Save button',
      expectedAfterState: 'File is saved and Notepad title bar updates',
      completionCondition: 'File saved successfully in Notepad',
      verificationMethod: 'visual_state_change',
    },
  ],
}
