import { Workflow } from '../types/workflow'

export const powerpointInsertImage: Workflow = {
  id: 'powerpoint_insert_image',
  application: 'powerpoint',
  task: 'insert_image',
  name: 'Insert Image',
  description: 'Insert a picture from your device into a PowerPoint slide',
  levels: [
    {
      levelNumber: 1,
      id: 'select_slide_canvas',
      title: 'Select slide area',
      instruction: 'Click on the central slide canvas where you want the image placed.',
      voiceInstruction: 'Click on the slide canvas area.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Slide Canvas',
      targetDescription: 'The central presentation slide canvas in PowerPoint',
      expectedBeforeState: 'Slide open in editor',
      expectedAction: 'User clicks on the slide workspace',
      expectedAfterState: 'Slide canvas has focus',
      completionCondition: 'Slide canvas is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'open_insert_tab',
      title: 'Click Insert tab',
      instruction: 'In the top PowerPoint ribbon, click on the "Insert" tab.',
      voiceInstruction: 'Click the Insert tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'Insert',
      targetDescription: 'The Insert tab in the PowerPoint top ribbon menu',
      expectedBeforeState: 'Slide canvas active',
      expectedAction: 'User clicks Insert tab',
      expectedAfterState: 'Insert ribbon tab is active showing Pictures button',
      completionCondition: 'Insert tab in PowerPoint ribbon is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'click_pictures_button',
      title: 'Click Pictures',
      instruction: 'In the Images group on the Insert ribbon, click "Pictures" and select "This Device".',
      voiceInstruction: 'Click Pictures and choose This Device.',
      targetType: 'BUTTON',
      targetText: 'Pictures',
      targetDescription: 'The Pictures dropdown button in the PowerPoint Insert ribbon',
      expectedBeforeState: 'Insert ribbon active with Pictures button visible',
      expectedAction: 'User clicks Pictures and chooses an image file',
      expectedAfterState: 'Picture object is placed on the slide canvas',
      completionCondition: 'Picture element is inserted into slide',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_picture_inserted',
      title: 'Verify picture inserted',
      instruction: 'Verify that the picture is placed on the slide and handles appear around it.',
      voiceInstruction: 'Verify that your picture is inserted into the slide.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Slide Canvas',
      targetDescription: 'The slide canvas displaying the newly inserted picture',
      expectedBeforeState: 'Picture inserted',
      expectedAction: 'User confirms picture position',
      expectedAfterState: 'Picture object with resize handles is active on slide',
      completionCondition: 'Picture object exists on slide',
      verificationMethod: 'visual_state_change',
    },
  ],
}
