import { Workflow } from '../types/workflow'

export const powerpointAddSlide: Workflow = {
  id: 'powerpoint_add_slide',
  application: 'powerpoint',
  task: 'add_slide',
  name: 'Add a New Slide',
  description: 'Add a new slide to your PowerPoint presentation',
  levels: [
    {
      levelNumber: 1,
      id: 'select_slide_panel',
      title: 'Select slide',
      instruction: 'Click on a slide in the left thumbnail panel where you want to insert after.',
      voiceInstruction: 'Select the slide in the left panel you want to insert after.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Slide Thumbnail',
      targetDescription: 'The slide thumbnail preview in the left PowerPoint slide navigation deck',
      expectedBeforeState: 'PowerPoint presentation open',
      expectedAction: 'User selects a slide thumbnail',
      expectedAfterState: 'Selected slide thumbnail is highlighted',
      completionCondition: 'Slide is selected in presentation',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'open_home_tab',
      title: 'Click Home tab',
      instruction: 'In the top PowerPoint ribbon, click on the "Home" tab.',
      voiceInstruction: 'Click the Home tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'Home',
      targetDescription: 'The Home tab in the PowerPoint top ribbon',
      expectedBeforeState: 'Slide selected',
      expectedAction: 'User clicks Home tab',
      expectedAfterState: 'Home ribbon active displaying New Slide button',
      completionCondition: 'Home tab in PowerPoint ribbon is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'click_new_slide',
      title: 'Click New Slide',
      instruction: 'In the Slides group on the Home ribbon, click "New Slide".',
      voiceInstruction: 'Click New Slide in the top ribbon.',
      targetType: 'BUTTON',
      targetText: 'New Slide',
      targetDescription: 'The New Slide button in the PowerPoint Home ribbon',
      expectedBeforeState: 'Home ribbon visible with New Slide button',
      expectedAction: 'User clicks New Slide',
      expectedAfterState: 'A new slide is inserted into the presentation',
      completionCondition: 'New slide appears in slide deck',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_new_slide',
      title: 'Verify slide created',
      instruction: 'Verify that the new slide is created and ready for editing.',
      voiceInstruction: 'Verify that your new slide is added.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Slide Canvas',
      targetDescription: 'The newly created slide canvas area in PowerPoint',
      expectedBeforeState: 'New slide created',
      expectedAction: 'User confirms new slide presence',
      expectedAfterState: 'New slide canvas is active on screen',
      completionCondition: 'New slide is active in presentation',
      verificationMethod: 'visual_state_change',
    },
  ],
}
