import { Workflow } from '../types/workflow'

export const powerpointAddTransition: Workflow = {
  id: 'powerpoint_add_transition',
  application: 'powerpoint',
  task: 'add_transition',
  name: 'Add Slide Transition',
  description: 'Add a transition effect to a PowerPoint slide',
  levels: [
    {
      levelNumber: 1,
      id: 'select_target_slide',
      title: 'Select slide',
      instruction: 'Click on the slide in the left thumbnail panel you want to add a transition to.',
      voiceInstruction: 'Select the slide you want to animate with a transition.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Slide Thumbnail',
      targetDescription: 'The slide thumbnail preview in the left PowerPoint slide deck',
      expectedBeforeState: 'Slide unselected or another slide active',
      expectedAction: 'User clicks slide thumbnail',
      expectedAfterState: 'Target slide is active in PowerPoint',
      completionCondition: 'Target slide is selected in presentation',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'open_transitions_tab',
      title: 'Click Transitions tab',
      instruction: 'In the top PowerPoint ribbon, click on the "Transitions" tab.',
      voiceInstruction: 'Click the Transitions tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'Transitions',
      targetDescription: 'The Transitions tab in the PowerPoint top ribbon menu',
      expectedBeforeState: 'Target slide selected',
      expectedAction: 'User clicks Transitions tab',
      expectedAfterState: 'Transitions gallery is displayed in the ribbon',
      completionCondition: 'Transitions tab in PowerPoint ribbon is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'choose_transition_style',
      title: 'Choose transition style',
      instruction: 'In the Transition to This Slide gallery, click a style like "Fade" or "Push".',
      voiceInstruction: 'Click a transition style like Fade or Push.',
      targetType: 'BUTTON',
      targetText: 'Fade',
      targetDescription: 'A transition style preset such as Fade, Push, or Morph in the ribbon gallery',
      expectedBeforeState: 'Transitions gallery visible',
      expectedAction: 'User clicks transition preset',
      expectedAfterState: 'Transition effect is applied to the slide',
      completionCondition: 'Transition style is selected and applied to slide',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_transition',
      title: 'Verify transition applied',
      instruction: 'Verify that a star animation icon appears next to the slide thumbnail in the left deck.',
      voiceInstruction: 'Verify that the transition star icon appears on your slide thumbnail.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Slide Thumbnail',
      targetDescription: 'The slide thumbnail showing the active transition animation icon',
      expectedBeforeState: 'Transition applied',
      expectedAction: 'User verifies transition indicator',
      expectedAfterState: 'Star icon is visible on the slide thumbnail',
      completionCondition: 'Transition icon appears on slide',
      verificationMethod: 'visual_state_change',
    },
  ],
}
