import { Workflow } from '../types/workflow'

export const wordFormatHeading: Workflow = {
  id: 'word_format_heading',
  application: 'word',
  task: 'format_heading',
  name: 'Format Text as Heading',
  description: 'Format selected text as a Heading 1 in Microsoft Word',
  levels: [
    {
      levelNumber: 1,
      id: 'select_text',
      title: 'Select the text',
      instruction: 'Click and drag to highlight the text you want to format as a heading.',
      voiceInstruction: 'Select the text you want to format as a heading.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Document Body',
      targetDescription: 'The Word document editing area containing your text',
      expectedBeforeState: 'Text cursor placed in document',
      expectedAction: 'User highlights a line of text',
      expectedAfterState: 'Text selection is active',
      completionCondition: 'Text is highlighted in Word document',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'click_home_tab',
      title: 'Click Home tab',
      instruction: 'In the top Word ribbon, click on the "Home" tab.',
      voiceInstruction: 'Click the Home tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'Home',
      targetDescription: 'The Home tab in the top Word ribbon menu',
      expectedBeforeState: 'Word document active with text selected',
      expectedAction: 'User clicks Home tab',
      expectedAfterState: 'Home ribbon tab is active displaying the Styles gallery',
      completionCondition: 'Home tab in Word ribbon is selected',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'click_heading_1',
      title: 'Click Heading 1',
      instruction: 'In the Styles group on the Home ribbon, click "Heading 1".',
      voiceInstruction: 'Click Heading 1 in the Styles gallery.',
      targetType: 'BUTTON',
      targetText: 'Heading 1',
      targetDescription: 'The Heading 1 style tile in the Word Styles gallery',
      expectedBeforeState: 'Styles gallery visible on Home tab',
      expectedAction: 'User clicks Heading 1 style',
      expectedAfterState: 'Heading 1 style is applied to selected text',
      completionCondition: 'Heading 1 style is applied to the text',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_heading',
      title: 'Verify heading formatted',
      instruction: 'Verify that the text has been styled as a larger, bold Heading 1.',
      voiceInstruction: 'Verify that your text is formatted as a heading.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Document Body',
      targetDescription: 'The styled heading text in the document',
      expectedBeforeState: 'Style applied',
      expectedAction: 'User verifies the heading formatting',
      expectedAfterState: 'Text appears in Heading 1 font and color',
      completionCondition: 'Heading 1 style is confirmed active',
      verificationMethod: 'visual_state_change',
    },
  ],
}
