import { Workflow } from '../types/workflow'

export const wordInsertTable: Workflow = {
  id: 'word_insert_table',
  application: 'word',
  task: 'insert_table',
  name: 'Insert Table',
  description: 'Insert a 3x3 table into Microsoft Word document',
  levels: [
    {
      levelNumber: 1,
      id: 'place_cursor',
      title: 'Place cursor',
      instruction: 'Click to place your typing cursor where you want the table to appear.',
      voiceInstruction: 'Click where you want the table inserted in your document.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Document Body',
      targetDescription: 'The Word document editing canvas area',
      expectedBeforeState: 'Document open and editable',
      expectedAction: 'User clicks on document location',
      expectedAfterState: 'Cursor is positioned at the insertion point',
      completionCondition: 'Cursor positioned in document body',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'open_insert_tab',
      title: 'Open Insert tab',
      instruction: 'Click on the "Insert" tab in the top Word ribbon.',
      voiceInstruction: 'Click on the Insert tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'Insert',
      targetDescription: 'The Insert tab in the Microsoft Word top ribbon',
      expectedBeforeState: 'Home or another ribbon tab active',
      expectedAction: 'User clicks Insert tab',
      expectedAfterState: 'Insert ribbon active displaying Table button',
      completionCondition: 'Insert tab in Word ribbon is active',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'click_table_button',
      title: 'Click Table',
      instruction: 'In the Tables group, click "Table" and choose a grid size (e.g. 3x3).',
      voiceInstruction: 'Click Table and choose a 3 by 3 grid.',
      targetType: 'BUTTON',
      targetText: 'Table',
      targetDescription: 'The Table dropdown button in the Insert ribbon',
      expectedBeforeState: 'Insert ribbon active with Table button visible',
      expectedAction: 'User clicks Table and selects 3x3 cells',
      expectedAfterState: 'Table is created inside the Word document',
      completionCondition: 'Table grid is inserted into document',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_table',
      title: 'Verify table inserted',
      instruction: 'Verify that the table grid is visible and ready for text input.',
      voiceInstruction: 'Verify that your table is inserted into Word.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Document Body',
      targetDescription: 'The newly inserted table grid in the document',
      expectedBeforeState: 'Table created',
      expectedAction: 'User verifies table structure',
      expectedAfterState: 'Table with rows and columns is active on page',
      completionCondition: 'Table element exists in document',
      verificationMethod: 'visual_state_change',
    },
  ],
}
