import { Workflow } from '../types/workflow'

export const wordSpellCheck: Workflow = {
  id: 'word_spell_check',
  application: 'word',
  task: 'spell_check',
  name: 'Run Spell Check',
  description: 'Run Spelling & Grammar check in Microsoft Word',
  levels: [
    {
      levelNumber: 1,
      id: 'open_review_tab',
      title: 'Click Review tab',
      instruction: 'In the top Word ribbon, click on the "Review" tab.',
      voiceInstruction: 'Click the Review tab in the top ribbon.',
      targetType: 'TAB',
      targetText: 'Review',
      targetDescription: 'The Review tab in the Microsoft Word top ribbon menu',
      expectedBeforeState: 'Word document open with text',
      expectedAction: 'User clicks Review tab',
      expectedAfterState: 'Review ribbon active with Proofing / Editor tools visible',
      completionCondition: 'Review tab in Word ribbon is selected',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'click_spelling_button',
      title: 'Click Spelling & Grammar',
      instruction: 'In the Proofing group, click "Spelling & Grammar" (or "Editor").',
      voiceInstruction: 'Click Spelling and Grammar in the Proofing group.',
      targetType: 'BUTTON',
      targetText: 'Spelling',
      targetDescription: 'The Spelling & Grammar button or Editor icon in the Review ribbon',
      expectedBeforeState: 'Review tab active',
      expectedAction: 'User clicks Spelling & Grammar',
      expectedAfterState: 'The Editor / Proofing side pane opens on the right',
      completionCondition: 'Spelling check side pane is open',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'review_suggestions',
      title: 'Review suggestions',
      instruction: 'Review the suggested corrections in the Editor pane and click to accept or ignore.',
      voiceInstruction: 'Review and accept or ignore the suggested corrections.',
      targetType: 'BUTTON',
      targetText: 'Spelling',
      targetDescription: 'The correction suggestion card or action button in the Editor pane',
      expectedBeforeState: 'Editor pane showing suggestions',
      expectedAction: 'User clicks suggestion to correct error',
      expectedAfterState: 'Correction is applied to document',
      completionCondition: 'Spelling correction applied',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_spell_check',
      title: 'Verify spell check complete',
      instruction: 'Verify that the spelling check is complete and no errors remain.',
      voiceInstruction: 'Verify that your spell check is complete.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Document Body',
      targetDescription: 'The cleaned Word document body',
      expectedBeforeState: 'Proofing review in progress or complete',
      expectedAction: 'User confirms document proofing status',
      expectedAfterState: 'Document has no spelling review flags',
      completionCondition: 'Spelling check completed successfully',
      verificationMethod: 'visual_state_change',
    },
  ],
}
