import { Workflow } from '../types/workflow'

export const youtubeFullscreen: Workflow = {
  id: 'youtube_fullscreen',
  application: 'chrome_youtube',
  task: 'fullscreen_video',
  name: 'Full Screen Video on YouTube',
  description: 'Maximize the YouTube video player to full screen for immersive viewing',
  levels: [
    {
      levelNumber: 1,
      id: 'play_video',
      title: 'Ensure Video is Playing',
      instruction: 'Make sure a video is currently playing on YouTube.',
      voiceInstruction: 'Ensure the video you want to maximize is playing.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Video Player',
      targetDescription: 'The active YouTube video playback window',
      expectedBeforeState: 'YouTube video watch page open',
      expectedAction: 'User confirms video playback',
      expectedAfterState: 'Video is active',
      completionCondition: 'Video is playing',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'hover_video_controls',
      title: 'Hover Over Video Player',
      instruction: 'Move your mouse cursor over the video player to show the bottom control bar.',
      voiceInstruction: 'Move your mouse over the video to show playback controls.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Video Player Controls',
      targetDescription: 'The bottom controls bar showing play, volume, time, and fullscreen',
      expectedBeforeState: 'Video playing',
      expectedAction: 'User hovers cursor over video',
      expectedAfterState: 'Player bottom control bar is visible',
      completionCondition: 'Player controls visible',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'click_fullscreen_button',
      title: 'Click Fullscreen Button',
      instruction: 'Click the Full Screen square icon in the bottom-right corner of the player (or press "f" on your keyboard).',
      voiceInstruction: 'Click the Full screen icon in the bottom right or press F.',
      targetType: 'BUTTON',
      targetText: 'Full screen',
      targetDescription: 'The Full screen icon button in the player control bar',
      expectedBeforeState: 'Controls bar visible',
      expectedAction: 'User clicks Full screen button or presses "f"',
      expectedAfterState: 'Video expands to cover entire display',
      completionCondition: 'Full screen mode enabled',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'verify_fullscreen_active',
      title: 'Verify Full Screen Active',
      instruction: 'Verify that the video is now filling your entire screen. Press "f" or Esc anytime to exit.',
      voiceInstruction: 'Verify that full screen is active. Press Escape anytime to exit.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Full Screen Video',
      targetDescription: 'The full screen video viewport occupying 100% of the display',
      expectedBeforeState: 'Fullscreen requested',
      expectedAction: 'User enjoys fullscreen playback',
      expectedAfterState: 'Fullscreen active',
      completionCondition: 'Display is in full screen mode',
      verificationMethod: 'visual_state_change',
    },
  ],
}
