import { Workflow } from '../types/workflow'

export const youtubeSearch: Workflow = {
  id: 'youtube_search',
  application: 'chrome_youtube',
  task: 'search_video',
  name: 'Search for Video on YouTube',
  description: 'Search for topics, creators, or videos on YouTube and open the result',
  levels: [
    {
      levelNumber: 1,
      id: 'click_youtube_search_bar',
      title: 'Click Search Bar',
      instruction: 'Click inside the search bar at the top of YouTube.',
      voiceInstruction: 'Click the YouTube search bar at the top.',
      targetType: 'INPUT',
      targetText: 'Search',
      targetDescription: 'The central search input bar on YouTube',
      expectedBeforeState: 'YouTube home or browse page active',
      expectedAction: 'User clicks search input',
      expectedAfterState: 'Search bar focused with active text cursor',
      completionCondition: 'Search bar is focused',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 2,
      id: 'type_search_query',
      title: 'Type Search Query',
      instruction: 'Type your search keywords into the search box.',
      voiceInstruction: 'Type the video or topic you want to search for.',
      targetType: 'INPUT',
      targetText: 'Search',
      targetDescription: 'The search box with entered keywords',
      expectedBeforeState: 'Search bar focused',
      expectedAction: 'User types search terms',
      expectedAfterState: 'Keywords entered and autocomplete dropdown appears',
      completionCondition: 'Search query entered',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 3,
      id: 'execute_search',
      title: 'Press Enter or Click Search',
      instruction: 'Press Enter on your keyboard or click the magnifying glass Search button.',
      voiceInstruction: 'Press Enter or click the search icon.',
      targetType: 'BUTTON',
      targetText: 'Search',
      targetDescription: 'The magnifying glass icon search button next to the input',
      expectedBeforeState: 'Query entered in search bar',
      expectedAction: 'User presses Enter or clicks search button',
      expectedAfterState: 'YouTube search results page loads (results list visible)',
      completionCondition: 'Search results displayed',
      verificationMethod: 'visual_state_change',
    },
    {
      levelNumber: 4,
      id: 'select_video_result',
      title: 'Click Video to Play',
      instruction: 'Click on the video thumbnail or title of the best matching result to start playback.',
      voiceInstruction: 'Click the video result to start playing it.',
      targetType: 'CANVAS_OBJECT',
      targetText: 'Video Result',
      targetDescription: 'The video thumbnail or title in the search results list',
      expectedBeforeState: 'Search results list displayed',
      expectedAction: 'User clicks video thumbnail or title',
      expectedAfterState: 'Video watch page loads and video starts playing',
      completionCondition: 'Video player is playing selected video',
      verificationMethod: 'visual_state_change',
    },
  ],
}
